on:
  schedule:
    - cron: '*/6 7-23 * * *'
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the description
        run: echo "Running the cron"
      - name: Making a call
        run: curl https://habituate-me-backend.onrender.com/authentication
